import React from "react";
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { ArrowLeft, BookOpenText, CheckCircle2, RefreshCcw, RotateCcw, ShieldAlert } from "lucide-react-native";
import { kwacha } from "@/lib/currency";
import { adminPostTicketOrganizationLiabilityEntry, getTicketOrganizationFinanceLedger, listAdminTicketOrganizationEvents, listAdminTicketOrganizationFinanceLedgers, type AdminTicketOrganizationEvent, type AdminTicketOrganizationFinanceLedgerSummary, type TicketOrganizationFinanceLedger } from "@/lib/ticketEventFinanceApi";

const ACCENT="#5e73dd",TEXT="#102a54",MUTED="#6e7892",BORDER="#e4e8f2";
type EntryType="liability_assessment"|"liability_repayment"|"liability_offset";
export default function OrganizationLiabilitiesScreen(){
  const router=useRouter();
  const [orgs,setOrgs]=React.useState<AdminTicketOrganizationFinanceLedgerSummary[]>([]),[selected,setSelected]=React.useState<string|null>(null),[ledger,setLedger]=React.useState<TicketOrganizationFinanceLedger|null>(null);
  const [events,setEvents]=React.useState<AdminTicketOrganizationEvent[]>([]),[selectedEvent,setSelectedEvent]=React.useState<string|null>(null);
  const selectedRef=React.useRef<string|null>(null);
  const [loading,setLoading]=React.useState(true),[refreshing,setRefreshing]=React.useState(false),[busy,setBusy]=React.useState(false),[entryType,setEntryType]=React.useState<EntryType>("liability_assessment"),[amount,setAmount]=React.useState(""),[memo,setMemo]=React.useState("");
  const load=React.useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);try{const rows=await listAdminTicketOrganizationFinanceLedgers();setOrgs(rows);const id=selectedRef.current||rows[0]?.organization_id||null;selectedRef.current=id;setSelected(id);if(id){const [nextLedger,nextEvents]=await Promise.all([getTicketOrganizationFinanceLedger(id),listAdminTicketOrganizationEvents(id)]);setLedger(nextLedger);setEvents(nextEvents);if(selectedEvent&&!nextEvents.some(e=>e.event_id===selectedEvent))setSelectedEvent(null);}else{setLedger(null);setEvents([]);}}catch(e:any){Alert.alert("Could not load ledgers",e?.message||"Try again.");}finally{setLoading(false);setRefreshing(false);}},[selectedEvent]);
  React.useEffect(()=>{void load();},[load]);
  const choose=async(id:string)=>{selectedRef.current=id;setSelected(id);setSelectedEvent(null);setLoading(true);try{const [nextLedger,nextEvents]=await Promise.all([getTicketOrganizationFinanceLedger(id),listAdminTicketOrganizationEvents(id)]);setLedger(nextLedger);setEvents(nextEvents);}catch(e:any){Alert.alert("Could not load ledger",e?.message||"Try again.");}finally{setLoading(false);}};
  const post=()=>{const value=Number(amount.replace(/,/g,"").trim());if(!Number.isInteger(value)||value<=0||memo.trim().length<3){Alert.alert("Complete the entry","Use a whole-MWK amount and a clear memo of at least 3 characters.");return;}Alert.alert("Post immutable ledger entry?",`${entryType.replace(/_/g," ")} · ${kwacha(value)}\n${selectedEvent?"Linked to the selected event.":"Organization-wide entry."}\n\nCorrections require a reversal entry.`,[{text:"Cancel",style:"cancel"},{text:"Post",onPress:async()=>{try{setBusy(true);await adminPostTicketOrganizationLiabilityEntry({organizationId:selected!,entryType,amountMwk:value,memo,eventId:selectedEvent});setAmount("");setMemo("");await load(true);}catch(e:any){Alert.alert("Could not post entry",e?.message||"Try again.");}finally{setBusy(false);}}}]);};
  const reverse=(entryId:string)=>{if(!memo.trim()){Alert.alert("Reversal memo required","Explain why the original entry must be reversed.");return;}Alert.alert("Reverse this entry?","The original remains visible and an opposite immutable entry will be posted.",[{text:"Cancel",style:"cancel"},{text:"Post reversal",style:"destructive",onPress:async()=>{try{setBusy(true);await adminPostTicketOrganizationLiabilityEntry({organizationId:selected!,entryType:"reversal",amountMwk:1,memo,reversesEntryId:entryId});setMemo("");await load(true);}catch(e:any){Alert.alert("Could not reverse entry",e?.message||"Try again.");}finally{setBusy(false);}}}]);};
  const selectedOrg=orgs.find(o=>o.organization_id===selected);
  return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={ACCENT}/>}>
    <View style={s.header}><Pressable style={s.icon} onPress={()=>router.back()}><ArrowLeft size={20} color={TEXT}/></Pressable><View style={{flex:1}}><Text style={s.kicker}>EYA Admin</Text><Text style={s.title}>Liability ledgers</Text></View><Pressable style={s.icon} onPress={()=>void load(true)}><RefreshCcw size={19} color={ACCENT}/></Pressable></View>
    <View style={s.notice}><ShieldAlert size={19} color="#946000"/><Text style={s.noticeText}>This is accounting authority only. Entries do not initiate, verify or execute any payment.</Text></View>
    {loading&&!orgs.length?<ActivityIndicator color={ACCENT}/>:orgs.length?<><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.orgRow}>{orgs.map(o=><Pressable key={o.organization_id} onPress={()=>void choose(o.organization_id)} style={[s.orgPill,selected===o.organization_id&&s.orgSelected]}><Text style={[s.orgText,selected===o.organization_id&&s.orgTextSelected]}>{o.organization_name}</Text><Text style={[s.orgBalance,selected===o.organization_id&&s.orgTextSelected]}>{kwacha(o.liability_balance_mwk)}</Text></Pressable>)}</ScrollView>
      <View style={s.balance}><Text style={s.label}>OUTSTANDING LIABILITY · {selectedOrg?.organization_name}</Text><Text style={[s.balanceValue,{color:(ledger?.liability_balance_mwk||0)>0?"#a32929":TEXT}]}>{kwacha(ledger?.liability_balance_mwk||0)}</Text></View>
      <View style={s.form}><Text style={s.section}>Post ledger entry</Text><View style={s.types}>{(["liability_assessment","liability_repayment","liability_offset"] as EntryType[]).map(t=><Pressable key={t} onPress={()=>setEntryType(t)} style={[s.type,entryType===t&&s.typeSelected]}><Text style={[s.typeText,entryType===t&&s.typeTextSelected]}>{t.split("_").slice(1).join(" ")}</Text></Pressable>)}</View><Text style={s.fieldLabel}>EVENT LINK · OPTIONAL</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.eventRow}><Pressable onPress={()=>setSelectedEvent(null)} style={[s.eventPill,!selectedEvent&&s.eventSelected]}><Text style={[s.eventText,!selectedEvent&&s.eventTextSelected]}>Organization-wide</Text></Pressable>{events.map(event=><Pressable key={event.event_id} onPress={()=>setSelectedEvent(event.event_id)} style={[s.eventPill,selectedEvent===event.event_id&&s.eventSelected]}><Text style={[s.eventText,selectedEvent===event.event_id&&s.eventTextSelected]}>{event.event_title}</Text></Pressable>)}</ScrollView><TextInput value={amount} onChangeText={setAmount} keyboardType="numeric" placeholder="Amount in MWK" placeholderTextColor="#9aa3b8" style={s.input}/><TextInput value={memo} onChangeText={setMemo} placeholder="Required audit memo" placeholderTextColor="#9aa3b8" style={s.input}/><Pressable disabled={busy||!selected} onPress={post} style={[s.post,busy&&{opacity:.5}]}>{busy?<ActivityIndicator color="#fff"/>:<CheckCircle2 size={17} color="#fff"/>}<Text style={s.postText}>Post immutable entry</Text></Pressable></View>
      <Text style={s.section}>History</Text>{ledger?.entries.length?ledger.entries.map(e=><View key={e.id} style={s.card}><View style={s.entryHead}><BookOpenText size={18} color={e.direction==="debit"?"#a32929":"#087443"}/><View style={{flex:1}}><Text style={s.entryTitle}>{e.entry_type.replace(/_/g," ")}</Text><Text style={s.meta}>{new Date(e.posted_at).toLocaleString()}</Text></View><Text style={[s.entryAmount,{color:e.direction==="debit"?"#a32929":"#087443"}]}>{e.direction==="debit"?"+":"−"}{kwacha(e.amount_mwk)}</Text></View><Text style={s.memo}>{e.memo}</Text>{e.entry_type!=="reversal"&&!ledger.entries.some(r=>r.reverses_entry_id===e.id)?<Pressable disabled={busy} onPress={()=>reverse(e.id)} style={s.reverse}><RotateCcw size={14} color="#a32929"/><Text style={s.reverseText}>Reverse using current memo</Text></Pressable>:null}</View>):<Text style={s.empty}>No ledger entries.</Text>}</>:<Text style={s.empty}>No ticket organizations exist yet.</Text>}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f5f7fc"},content:{padding:18,paddingBottom:70,gap:13},header:{flexDirection:"row",alignItems:"center",gap:12},icon:{width:44,height:44,borderRadius:22,backgroundColor:"#fff",borderWidth:1,borderColor:BORDER,alignItems:"center",justifyContent:"center"},kicker:{color:ACCENT,fontSize:10,fontWeight:"900",letterSpacing:1},title:{color:TEXT,fontSize:24,fontWeight:"900"},notice:{borderRadius:18,backgroundColor:"#fff4df",padding:13,flexDirection:"row",gap:9,alignItems:"flex-start"},noticeText:{flex:1,color:"#7a5200",fontSize:12,lineHeight:17,fontWeight:"800"},orgRow:{gap:8},orgPill:{minWidth:145,borderRadius:16,borderWidth:1,borderColor:BORDER,backgroundColor:"#fff",padding:11},orgSelected:{backgroundColor:ACCENT,borderColor:ACCENT},orgText:{color:TEXT,fontSize:12,fontWeight:"900"},orgTextSelected:{color:"#fff"},orgBalance:{color:MUTED,fontSize:10,fontWeight:"800",marginTop:3},balance:{borderRadius:22,backgroundColor:"#fff",borderWidth:1,borderColor:BORDER,padding:15},label:{color:MUTED,fontSize:9,fontWeight:"900",letterSpacing:.6},balanceValue:{fontSize:29,fontWeight:"900",marginTop:4},form:{borderRadius:22,backgroundColor:"#fff",borderWidth:1,borderColor:BORDER,padding:14,gap:10},section:{color:TEXT,fontSize:18,fontWeight:"900"},types:{flexDirection:"row",gap:6},type:{flex:1,minHeight:40,borderRadius:13,borderWidth:1,borderColor:BORDER,alignItems:"center",justifyContent:"center"},typeSelected:{backgroundColor:"#eef1ff",borderColor:ACCENT},typeText:{color:MUTED,fontSize:9,fontWeight:"900",textTransform:"capitalize"},typeTextSelected:{color:ACCENT},fieldLabel:{color:MUTED,fontSize:9,fontWeight:"900",letterSpacing:.7},eventRow:{gap:6},eventPill:{minHeight:35,borderRadius:13,borderWidth:1,borderColor:BORDER,paddingHorizontal:10,alignItems:"center",justifyContent:"center"},eventSelected:{backgroundColor:"#eef1ff",borderColor:ACCENT},eventText:{color:MUTED,fontSize:10,fontWeight:"800"},eventTextSelected:{color:ACCENT},input:{minHeight:46,borderRadius:14,borderWidth:1,borderColor:BORDER,paddingHorizontal:12,color:TEXT,fontWeight:"800"},post:{minHeight:47,borderRadius:15,backgroundColor:ACCENT,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:6},postText:{color:"#fff",fontWeight:"900"},card:{borderRadius:19,backgroundColor:"#fff",borderWidth:1,borderColor:BORDER,padding:14,gap:8},entryHead:{flexDirection:"row",gap:9,alignItems:"flex-start"},entryTitle:{color:TEXT,fontSize:13,fontWeight:"900",textTransform:"capitalize"},meta:{color:MUTED,fontSize:10,fontWeight:"700",marginTop:2},entryAmount:{fontSize:12,fontWeight:"900"},memo:{color:MUTED,fontSize:11,lineHeight:16,fontWeight:"700"},reverse:{alignSelf:"flex-start",borderRadius:14,backgroundColor:"#fff0f0",paddingHorizontal:10,minHeight:32,flexDirection:"row",gap:5,alignItems:"center"},reverseText:{color:"#a32929",fontSize:9,fontWeight:"900"},empty:{color:MUTED,textAlign:"center",padding:25,fontWeight:"700"}});
