import React from "react";
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";
import { ArrowLeft, CheckCircle2, Landmark, RefreshCcw, ShieldCheck, Smartphone, XCircle } from "lucide-react-native";
import { adminReviewTicketPayoutDestination, listAdminTicketPayoutDestinations, type TicketPayoutDestination } from "@/lib/ticketEventFinanceApi";

const ACCENT="#5e73dd", TEXT="#102a54", MUTED="#6e7892", BORDER="#e4e8f2";
export default function AdminPayoutDestinationsScreen() {
  const router=useRouter();
  const [rows,setRows]=React.useState<TicketPayoutDestination[]>([]), [loading,setLoading]=React.useState(true), [refreshing,setRefreshing]=React.useState(false), [busy,setBusy]=React.useState<string|null>(null);
  const [notes,setNotes]=React.useState<Record<string,string>>({});
  const load=React.useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);try{setRows(await listAdminTicketPayoutDestinations());}catch(e:any){Alert.alert("Could not load destinations",e?.message||"Try again.");}finally{setLoading(false);setRefreshing(false);}},[]);
  React.useEffect(()=>{void load();},[load]);
  const review=(row:TicketPayoutDestination,action:"verify"|"reject"|"disable")=>{
    const note=(notes[row.id]||"").trim();
    if(action!=="verify"&&!note){Alert.alert("Reason required","Add a review note for rejection or disabling.");return;}
    Alert.alert(`${action[0].toUpperCase()+action.slice(1)} destination?`, action==="verify"?"This will make the destination verified and primary. Only masked details are visible here.":note,[{text:"Cancel",style:"cancel"},{text:action[0].toUpperCase()+action.slice(1),style:action==="verify"?"default":"destructive",onPress:async()=>{try{setBusy(row.id);await adminReviewTicketPayoutDestination({destinationId:row.id,action,makePrimary:action==="verify",note});await load(true);}catch(e:any){Alert.alert("Review failed",e?.message||"Try again.");}finally{setBusy(null);}}}]);
  };
  return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={ACCENT}/>}>
    <View style={s.header}><Pressable style={s.icon} onPress={()=>router.back()}><ArrowLeft size={20} color={TEXT}/></Pressable><View style={{flex:1}}><Text style={s.kicker}>EYA Admin</Text><Text style={s.title}>Payout destinations</Text></View><Pressable style={s.icon} onPress={()=>void load(true)}><RefreshCcw size={19} color={ACCENT}/></Pressable></View>
    <View style={s.notice}><ShieldCheck size={19} color="#087443"/><Text style={s.noticeText}>Review identity and masked destination details only. Verification makes a destination eligible for payout-request binding; it does not send money.</Text></View>
    {loading?<ActivityIndicator color={ACCENT}/>:rows.length?rows.map(row=><View key={row.id} style={s.card}><View style={s.row}>{row.method==="bank"?<Landmark size={21} color={ACCENT}/>:<Smartphone size={21} color={ACCENT}/>}<View style={{flex:1}}><Text style={s.name}>{row.organization_name||"Organization"}</Text><Text style={s.meta}>{row.beneficiary_name} · {row.bank_or_network}</Text><Text style={s.destination}>{row.masked_destination}</Text></View><Text style={[s.status,{color:row.status==="verified"?"#087443":row.status==="pending_verification"?"#946000":"#a32929"}]}>{row.status.replace(/_/g," ")}</Text></View>{row.review_note?<Text style={s.meta}>Previous note: {row.review_note}</Text>:null}<TextInput value={notes[row.id]||""} onChangeText={s=>setNotes(n=>({...n,[row.id]:s}))} placeholder="Review note (required to reject or disable)" placeholderTextColor="#9aa3b8" style={s.input}/>{row.status==="pending_verification"?<View style={s.actions}><Pressable disabled={busy===row.id} style={[s.btn,s.reject]} onPress={()=>review(row,"reject")}><XCircle size={16} color="#a32929"/><Text style={s.rejectText}>Reject</Text></Pressable><Pressable disabled={busy===row.id} style={[s.btn,s.verify]} onPress={()=>review(row,"verify")}>{busy===row.id?<ActivityIndicator color="#fff"/>:<CheckCircle2 size={16} color="#fff"/>}<Text style={s.verifyText}>Verify & make primary</Text></Pressable></View>:row.status==="verified"?<Pressable disabled={busy===row.id} style={[s.btn,s.reject]} onPress={()=>review(row,"disable")}><XCircle size={16} color="#a32929"/><Text style={s.rejectText}>Disable destination</Text></Pressable>:null}</View>):<Text style={s.empty}>No payout destinations submitted.</Text>}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f5f7fc"},content:{padding:18,paddingBottom:70,gap:13},header:{flexDirection:"row",alignItems:"center",gap:12},icon:{width:44,height:44,borderRadius:22,backgroundColor:"#fff",borderWidth:1,borderColor:BORDER,alignItems:"center",justifyContent:"center"},kicker:{color:ACCENT,fontSize:10,fontWeight:"900",letterSpacing:1},title:{color:TEXT,fontSize:24,fontWeight:"900"},notice:{borderRadius:18,backgroundColor:"#e8f7ee",padding:13,flexDirection:"row",gap:9,alignItems:"flex-start"},noticeText:{flex:1,color:"#276346",fontSize:12,lineHeight:17,fontWeight:"800"},card:{borderRadius:22,backgroundColor:"#fff",borderWidth:1,borderColor:BORDER,padding:14,gap:10},row:{flexDirection:"row",gap:10,alignItems:"flex-start"},name:{color:TEXT,fontSize:16,fontWeight:"900"},meta:{color:MUTED,fontSize:11,lineHeight:16,fontWeight:"700"},destination:{color:TEXT,fontSize:15,fontWeight:"900",marginTop:3},status:{fontSize:8,fontWeight:"900",textTransform:"uppercase",maxWidth:90,textAlign:"right"},input:{minHeight:45,borderRadius:14,borderWidth:1,borderColor:BORDER,paddingHorizontal:12,color:TEXT,fontWeight:"700"},actions:{flexDirection:"row",gap:8},btn:{flex:1,minHeight:45,borderRadius:15,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:5},reject:{backgroundColor:"#fff0f0"},verify:{backgroundColor:"#087443"},rejectText:{color:"#a32929",fontSize:11,fontWeight:"900"},verifyText:{color:"#fff",fontSize:11,fontWeight:"900"},empty:{color:MUTED,textAlign:"center",fontWeight:"700",padding:30}});
