import React from "react";
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useLocalSearchParams, useRouter } from "expo-router";
import { ArrowLeft, BookOpenText, ShieldCheck } from "lucide-react-native";
import { kwacha } from "@/lib/currency";
import { getTicketOrganizationFinanceLedger, type TicketOrganizationFinanceLedger } from "@/lib/ticketEventFinanceApi";
import { useStudentTheme } from "@/providers/StudentThemeProvider";

export default function FinanceLedgerScreen() {
  const router=useRouter(), {theme}=useStudentTheme();
  const p=useLocalSearchParams<{organizationId?:string;organizationName?:string;eventId?:string}>();
  const organizationId=String(p.organizationId||"");
  const [data,setData]=React.useState<TicketOrganizationFinanceLedger|null>(null),[loading,setLoading]=React.useState(true),[refreshing,setRefreshing]=React.useState(false),[error,setError]=React.useState<string|null>(null);
  const load=React.useCallback(async(refresh=false)=>{refresh?setRefreshing(true):setLoading(true);try{setError(null);setData(await getTicketOrganizationFinanceLedger(organizationId));}catch(e:any){setError(e?.message||"Could not load finance ledger.");}finally{setLoading(false);setRefreshing(false);}},[organizationId]);
  React.useEffect(()=>{void load();},[load]);
  const visibleEntries=p.eventId?data?.entries.filter(row=>row.event_id===p.eventId):data?.entries;
  const eventBalance=(visibleEntries||[]).reduce((sum,row)=>sum+(row.direction==="debit"?row.amount_mwk:-row.amount_mwk),0);
  return <SafeAreaView style={[s.root,{backgroundColor:theme.background}]}><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={theme.accent}/>}>
    <View style={s.header}><Pressable style={[s.back,{backgroundColor:theme.surface,borderColor:theme.border}]} onPress={()=>router.back()}><ArrowLeft size={20} color={theme.text}/></Pressable><View style={{flex:1}}><Text style={[s.title,{color:theme.heading}]}>Liability ledger</Text><Text style={[s.sub,{color:theme.textMuted}]}>{p.organizationName||"Organization"}</Text></View></View>
    <View style={[s.balance,{backgroundColor:theme.surface,borderColor:theme.borderSoft}]}><Text style={[s.balanceLabel,{color:theme.textMuted}]}>{p.eventId?"EVENT-LINKED LIABILITY":"OUTSTANDING ORGANIZATION LIABILITY"}</Text><Text style={[s.balanceValue,{color:(p.eventId?eventBalance:data?.liability_balance_mwk)?"#a32929":theme.heading}]}>{kwacha(p.eventId?Math.max(eventBalance,0):(data?.liability_balance_mwk||0))}</Text>{p.eventId?<Text style={[s.orgTotal,{color:theme.textMuted}]}>Organization total: {kwacha(data?.liability_balance_mwk||0)}</Text>:null}<View style={s.note}><ShieldCheck size={17} color="#087443"/><Text style={s.noteText}>Entries are append-only. Corrections appear as reversals instead of changing history.</Text></View></View>
    {loading?<ActivityIndicator color={theme.accent}/>:error?<Text style={s.error}>{error}</Text>:visibleEntries?.length?visibleEntries.map(row=><View key={row.id} style={[s.card,{backgroundColor:theme.surface,borderColor:theme.borderSoft}]}><View style={s.row}><BookOpenText size={18} color={row.direction==="debit"?"#a32929":"#087443"}/><View style={{flex:1}}><Text style={[s.entryTitle,{color:theme.text}]}>{row.entry_type.replace(/_/g," ")}</Text><Text style={[s.meta,{color:theme.textMuted}]}>{new Date(row.posted_at).toLocaleString()}</Text></View><Text style={[s.amount,{color:row.direction==="debit"?"#a32929":"#087443"}]}>{row.direction==="debit"?"+":"−"}{kwacha(row.amount_mwk)}</Text></View><Text style={[s.memo,{color:theme.textMuted}]}>{row.memo}</Text></View>):<Text style={[s.empty,{color:theme.textMuted}]}>{p.eventId?"No liability entries are linked to this event.":"No liability entries. The organization balance is clear."}</Text>}
  </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({root:{flex:1},content:{padding:16,paddingBottom:60,gap:13},header:{flexDirection:"row",alignItems:"center",gap:12},back:{width:44,height:44,borderRadius:22,borderWidth:1,alignItems:"center",justifyContent:"center"},title:{fontSize:25,fontWeight:"900"},sub:{fontSize:12,fontWeight:"700",marginTop:2},balance:{borderRadius:23,borderWidth:1,padding:16,gap:7},balanceLabel:{fontSize:9,fontWeight:"900",letterSpacing:.7},balanceValue:{fontSize:29,fontWeight:"900"},orgTotal:{fontSize:11,fontWeight:"800"},note:{flexDirection:"row",gap:7,alignItems:"flex-start",backgroundColor:"#e8f7ee",borderRadius:14,padding:10},noteText:{flex:1,color:"#276346",fontSize:10,lineHeight:15,fontWeight:"800"},card:{borderRadius:19,borderWidth:1,padding:14,gap:8},row:{flexDirection:"row",alignItems:"flex-start",gap:9},entryTitle:{fontSize:14,fontWeight:"900",textTransform:"capitalize"},meta:{fontSize:10,fontWeight:"700",marginTop:2},amount:{fontSize:13,fontWeight:"900"},memo:{fontSize:11,lineHeight:16,fontWeight:"700"},error:{color:"#a32929",textAlign:"center",fontWeight:"800",padding:20},empty:{textAlign:"center",padding:26,fontWeight:"700"}});
